[tool]
id = “openapi”

[[dependency]] # tool jar
path = "../bal-openapi-tool-2.7.0.jar"

[[dependency]] # dependency jar
path = "resources/tool-lib/snakeyaml-1.26.jar"

[[dependency]] # dependency jar
path = "resources/tool-lib/commons-logging-1.2.jar"